name: Automation Tests on PR Comment
# on:
#   issue_comment:                                     
#     types: [created, edited, deleted]

on: pull_request_review_comment
# on: pull_request_review

jobs:
  automation-tests:
    runs-on: ubuntu-latest
    # if: github.event.issue.pull_request && contains(github.event.comment.body, '/tests')
    steps:
    # - name: Run Automation Tests
    #   run: echo Run Automation Tests

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
